// AUTOMATISCH ERZEUGT aus Wikidata/Wikipedia (gemeinfreie Werke, Bilder von Wikimedia Commons). Bauhaus-Ergänzung.
import type { PainterData, Style, WorkData } from "./art-data";

export const extraStyles3: Style[] = [
  { slug: "bauhaus", name: "Bauhaus", period: "1919–1933", description: "Die Weimarer und Dessauer Schule vereinte Kunst, Handwerk und Technik – ihre Meister prägten die Moderne entscheidend." },
];

export const extraPainters3: PainterData[] = [
  { slug: "laszlo-moholy-nagy", name: "László Moholy-Nagy", life: "1895–1946", origin: "", epoch: "moderne", styles: ["bauhaus","konstruktivismus"], bio: "László Moholy-Nagy (IPA: [ˈlaːsloː ˈmoholiˌnɒɟ]) (geborener László Weisz; * 20. Juli 1895 in Bácsborsód, Österreich-Ungarn; † 24." },
  { slug: "oskar-schlemmer", name: "Oskar Schlemmer", life: "1888–1943", origin: "", epoch: "moderne", styles: ["bauhaus"], bio: "Oskar Schlemmer (* 4. September 1888 in Stuttgart; † 13." },
  { slug: "lyonel-feininger", name: "Lyonel Feininger", life: "1871–1956", origin: "New York, USA", epoch: "moderne", styles: ["bauhaus","expressionismus","kubismus"], bio: "Deutsch-amerikanischer Maler und Grafiker und einer der ersten Meister am Bauhaus in Weimar. Seine kristallin gebrochenen Kirchen- und Stadtansichten verbinden Kubismus und Expressionismus zu einer ganz eigenen Bildsprache." },
];

export const extraWorks3: WorkData[] = [
  { id: "z-vii", title: "Z VII", year: "1926", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Z%20vii.png?width=1200", painter: "laszlo-moholy-nagy", museum: "National Gallery of Art", technique: "", styles: ["bauhaus","konstruktivismus"], description: "„Z VII“ ist ein Werk von László Moholy-Nagy aus dem Jahr 1926.", significance: "Ein charakteristisches Werk aus dem Schaffen von László Moholy-Nagy.", reception: "" },
  { id: "die-grosse-gefuehlsmaschine", title: "Die grosse Gefühlsmaschine", year: "1920", image: "https://commons.wikimedia.org/wiki/Special:FilePath/L%C3%A0szlo%20moholy-nagy%2C%20la%20grande%20macchina%20delle%20emozioni%2C%201920.jpg?width=1200", painter: "laszlo-moholy-nagy", museum: "Van Abbemuseum", technique: "Ölfarbe", styles: ["bauhaus","konstruktivismus"], description: "„Die grosse Gefühlsmaschine“ ist ein Werk von László Moholy-Nagy aus dem Jahr 1920.", significance: "Ein charakteristisches Werk aus dem Schaffen von László Moholy-Nagy.", reception: "" },
  { id: "lis-moholy-nagy", title: "LIS (Moholy-Nagy)", year: "1922", image: "https://commons.wikimedia.org/wiki/Special:FilePath/L%C3%A1szl%C3%B3%20Moholy-Nagy%20-%20LIS%20-%201981-0006%20-%20Kunsthaus%20Z%C3%BCrich.jpg?width=1200", painter: "laszlo-moholy-nagy", museum: "Kunsthaus Zürich", technique: "Ölfarbe", styles: ["bauhaus","konstruktivismus"], description: "„LIS (Moholy-Nagy)“ ist ein Werk von László Moholy-Nagy aus dem Jahr 1922.", significance: "Ein charakteristisches Werk aus dem Schaffen von László Moholy-Nagy.", reception: "" },
  { id: "komposition-z-viii", title: "Komposition Z VIII", year: "1950", image: "https://commons.wikimedia.org/wiki/Special:FilePath/L%C3%A1szl%C3%B3%20Moholy-Nagy%2C%20Z%20VIII%2C%201924%20(musei%20di%20berlino).jpg?width=1200", painter: "laszlo-moholy-nagy", museum: "Neue Nationalgalerie", technique: "Graphit", styles: ["bauhaus","konstruktivismus"], description: "„Komposition Z VIII“ ist ein Werk von László Moholy-Nagy aus dem Jahr 1950.", significance: "Ein charakteristisches Werk aus dem Schaffen von László Moholy-Nagy.", reception: "" },
  { id: "konstruktion", title: "Konstruktion", year: "1924", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Construction%20(SM%20lg71).png?width=1200", painter: "laszlo-moholy-nagy", museum: "Städelsches Kunstinstitut", technique: "Ölfarbe", styles: ["bauhaus","konstruktivismus"], description: "„Konstruktion“ ist ein Werk von László Moholy-Nagy aus dem Jahr 1924.", significance: "Ein charakteristisches Werk aus dem Schaffen von László Moholy-Nagy.", reception: "" },
  { id: "e-iv-konstruktion-vii", title: "E IV (Konstruktion VII)", year: "1922", image: "https://commons.wikimedia.org/wiki/Special:FilePath/L%C3%A1szl%C3%B3%20Moholy-Nagy%20-%20E%20IV%20(Konstruktion%20VII)%20-%202752%20-%20Staatliche%20Kunsthalle%20Karlsruhe.jpg?width=1200", painter: "laszlo-moholy-nagy", museum: "Staatliche Kunsthalle Karlsruhe", technique: "Ölfarbe", styles: ["bauhaus","konstruktivismus"], description: "„E IV (Konstruktion VII)“ ist ein Werk von László Moholy-Nagy aus dem Jahr 1922.", significance: "Ein charakteristisches Werk aus dem Schaffen von László Moholy-Nagy.", reception: "" },
  { id: "ch3-al", title: "CH3 Al", year: "1938", image: "https://commons.wikimedia.org/wiki/Special:FilePath/L%C3%A1szl%C3%B3%20Moholy-Nagy%20-%20CH3%20Al%2C%201938.jpg?width=1200", painter: "laszlo-moholy-nagy", museum: "", technique: "", styles: ["bauhaus","konstruktivismus"], description: "„CH3 Al“ ist ein Werk von László Moholy-Nagy aus dem Jahr 1938.", significance: "Ein charakteristisches Werk aus dem Schaffen von László Moholy-Nagy.", reception: "" },
  { id: "leda-y-el-cisne", title: "Leda y el cisne", year: "", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Leda%20i%20el%20cigne%20(Leda%20and%20the%20Swan)%2C%20L%C3%A1szl%C3%B3%20Moholy-Nagy.%20Plexiglas%2C%2055%2C9%20x%2041%2C3%20x%2040%20cm.%20-%20Institut%20Valenci%C3%A0%20d'Art%20Modern.png?width=1200", painter: "laszlo-moholy-nagy", museum: "Institut für moderne Kunst Valencia", technique: "", styles: ["bauhaus","konstruktivismus"], description: "„Leda y el cisne“ ist ein Werk von László Moholy-Nagy.", significance: "Ein charakteristisches Werk aus dem Schaffen von László Moholy-Nagy.", reception: "" },
  { id: "bauhaustreppe", title: "Bauhaustreppe", year: "1932", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Oskar%20Schlemmer%20-%20Bauhaustreppe%201932.jpg?width=1200", painter: "oskar-schlemmer", museum: "Museum of Modern Art", technique: "Ölfarbe", styles: ["bauhaus"], description: "„Bauhaustreppe“ ist ein Werk von Oskar Schlemmer aus dem Jahr 1932.", significance: "Ein charakteristisches Werk aus dem Schaffen von Oskar Schlemmer.", reception: "" },
  { id: "konzentrische-gruppe", title: "Konzentrische Gruppe", year: "1925", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Konzentrische%20Gruppe%20-%20Oskar%20Schlemmer.jpg?width=1200", painter: "oskar-schlemmer", museum: "Staatsgalerie Stuttgart", technique: "Ölfarbe", styles: ["bauhaus"], description: "„Konzentrische Gruppe“ ist ein Werk von Oskar Schlemmer aus dem Jahr 1925.", significance: "Ein charakteristisches Werk aus dem Schaffen von Oskar Schlemmer.", reception: "" },
  { id: "gassenwinkel", title: "Gassenwinkel", year: "1911", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Oskar%20Schlemmer%20-%20Gassenwinkel%20-%204350%20-%20%C3%96sterreichische%20Galerie%20Belvedere.jpg?width=1200", painter: "oskar-schlemmer", museum: "Österreichische Galerie Belvedere", technique: "", styles: ["bauhaus"], description: "„Gassenwinkel“ ist ein Werk von Oskar Schlemmer aus dem Jahr 1911.", significance: "Ein charakteristisches Werk aus dem Schaffen von Oskar Schlemmer.", reception: "" },
  { id: "taenzerin-die-geste", title: "Tänzerin (Die Geste)", year: "1922", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Munich%20-%20Dancer%20by%20Oskar%20Schlemmer%2002.jpg?width=1200", painter: "oskar-schlemmer", museum: "Bayerische Staatsgemäldesammlungen", technique: "Tempera", styles: ["bauhaus"], description: "„Tänzerin (Die Geste)“ ist ein Werk von Oskar Schlemmer aus dem Jahr 1922.", significance: "Ein charakteristisches Werk aus dem Schaffen von Oskar Schlemmer.", reception: "" },
  { id: "jagdschloss-grunewald", title: "Jagdschloss Grunewald", year: "1912", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Oskar%20Schlemmer%20-%20Jagdschlo%C3%9F%20Grunewald%20-%20BG-M%200418-77%20-%20Berlinische%20Galerie.jpg?width=1200", painter: "oskar-schlemmer", museum: "Berlinische Galerie", technique: "Ölfarbe", styles: ["bauhaus"], description: "„Jagdschloss Grunewald“ ist ein Werk von Oskar Schlemmer aus dem Jahr 1912.", significance: "Ein charakteristisches Werk aus dem Schaffen von Oskar Schlemmer.", reception: "" },
  { id: "tischgesellschaft", title: "Tischgesellschaft", year: "1935", image: "https://commons.wikimedia.org/wiki/Special:FilePath/1935%20Schlemmer%20Tischgesellschaft%20anagoria.JPG?width=1200", painter: "oskar-schlemmer", museum: "Städelsches Kunstinstitut", technique: "Leinwand", styles: ["bauhaus"], description: "„Tischgesellschaft“ ist ein Werk von Oskar Schlemmer aus dem Jahr 1935.", significance: "Ein charakteristisches Werk aus dem Schaffen von Oskar Schlemmer.", reception: "" },
  { id: "roemisches-oder-vier-figuren-im-raum", title: "Römisches (oder: Vier Figuren im Raum)", year: "1925", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Oskar%20Schlemmer%20-%20Vier%20Figuren%20im%20Raum%201925.jpg?width=1200", painter: "oskar-schlemmer", museum: "Kunstmuseum Basel", technique: "Ölfarbe", styles: ["bauhaus"], description: "„Römisches (oder: Vier Figuren im Raum)“ ist ein Werk von Oskar Schlemmer aus dem Jahr 1925.", significance: "Ein charakteristisches Werk aus dem Schaffen von Oskar Schlemmer.", reception: "" },
  { id: "vase-mit-gladiolen-und-dahlien", title: "Vase mit Gladiolen und Dahlien", year: "1925", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Schlemmer%20A%20vase%20of%20gladiolus%20and%20dalias.jpg?width=1200", painter: "oskar-schlemmer", museum: "Muzeum Kolekcji im. Jana Pawła II", technique: "Ölfarbe", styles: ["bauhaus"], description: "„Vase mit Gladiolen und Dahlien“ ist ein Werk von Oskar Schlemmer aus dem Jahr 1925.", significance: "Ein charakteristisches Werk aus dem Schaffen von Oskar Schlemmer.", reception: "" },
  { id: "gelmeroda-iv", title: "Gelmeroda IV", year: "1915", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Feininger%2C%20Lyonel%20-%20Gelmeroda%20IV.jpg?width=1200", painter: "lyonel-feininger", museum: "", technique: "Öl auf Leinwand", styles: ["bauhaus","expressionismus"], description: "„Gelmeroda IV\" ist ein Werk von Lyonel Feininger aus dem Jahr 1915.", significance: "Ein charakteristisches Werk aus Feiningers Bauhaus-Zeit: Architektur wird zu schwebenden, lichtdurchwirkten Kristallformen.", reception: "" },
  { id: "gelmeroda-viii", title: "Gelmeroda VIII", year: "1921", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Gelmeroda%2C%20VIII%2C%20by%20Lyonel%20Feininger.jpg?width=1200", painter: "lyonel-feininger", museum: "Whitney Museum of American Art", technique: "Öl auf Leinwand", styles: ["bauhaus","expressionismus"], description: "„Gelmeroda VIII\" ist ein Werk von Lyonel Feininger aus dem Jahr 1921.", significance: "Ein charakteristisches Werk aus Feiningers Bauhaus-Zeit: Architektur wird zu schwebenden, lichtdurchwirkten Kristallformen.", reception: "" },
  { id: "roter-turm-ii", title: "Roter Turm II", year: "1930", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Lyonel%20Feininger%20-%20Roter%20Turm%20II%201930.jpg?width=1200", painter: "lyonel-feininger", museum: "", technique: "Öl auf Leinwand", styles: ["bauhaus","expressionismus"], description: "„Roter Turm II\" ist ein Werk von Lyonel Feininger aus dem Jahr 1930.", significance: "Ein charakteristisches Werk aus Feiningers Bauhaus-Zeit: Architektur wird zu schwebenden, lichtdurchwirkten Kristallformen.", reception: "" },
  { id: "der-dom-in-halle", title: "Der Dom in Halle", year: "1931", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Lyonel%20Feininger%20-%20Der%20Dom%20in%20Halle%201931.jpg?width=1200", painter: "lyonel-feininger", museum: "", technique: "Öl auf Leinwand", styles: ["bauhaus","expressionismus"], description: "„Der Dom in Halle\" ist ein Werk von Lyonel Feininger aus dem Jahr 1931.", significance: "Ein charakteristisches Werk aus Feiningers Bauhaus-Zeit: Architektur wird zu schwebenden, lichtdurchwirkten Kristallformen.", reception: "" },
  { id: "gasometer-berlin-schoeneberg", title: "Gasometer in Berlin-Schöneberg", year: "1912", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Lyonel%20Feininger%20-%20Gasometer%20in%20Berlin-Sch%C3%B6neberg%201912.jpg?width=1200", painter: "lyonel-feininger", museum: "", technique: "Öl auf Leinwand", styles: ["bauhaus","expressionismus"], description: "„Gasometer in Berlin-Schöneberg\" ist ein Werk von Lyonel Feininger aus dem Jahr 1912.", significance: "Ein charakteristisches Werk aus Feiningers Bauhaus-Zeit: Architektur wird zu schwebenden, lichtdurchwirkten Kristallformen.", reception: "" },
  { id: "dorfteich-von-gelmeroda", title: "Der Dorfteich von Gelmeroda", year: "1922", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Lyonel%20feininger%2C%20lo%20stagno%20del%20villaggio%20di%20gelmeroda%2C%201922.jpg?width=1200", painter: "lyonel-feininger", museum: "", technique: "Öl auf Leinwand", styles: ["bauhaus","expressionismus"], description: "„Der Dorfteich von Gelmeroda\" ist ein Werk von Lyonel Feininger aus dem Jahr 1922.", significance: "Ein charakteristisches Werk aus Feiningers Bauhaus-Zeit: Architektur wird zu schwebenden, lichtdurchwirkten Kristallformen.", reception: "" },
  { id: "bruecke-v", title: "Brücke V", year: "1919", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Lyonel%20feininger%2C%20ponte%20V%2C%201919%20(PMoA).jpg?width=1200", painter: "lyonel-feininger", museum: "Philadelphia Museum of Art", technique: "Öl auf Leinwand", styles: ["bauhaus","expressionismus"], description: "„Brücke V\" ist ein Werk von Lyonel Feininger aus dem Jahr 1919.", significance: "Ein charakteristisches Werk aus Feiningers Bauhaus-Zeit: Architektur wird zu schwebenden, lichtdurchwirkten Kristallformen.", reception: "" },
];
