/**
 * Besuchsinfos je Haus. Redaktionell gepflegt (Stand: Saison 2026) — Öffnungszeiten
 * ändern sich an Feiertagen und in Sonderöffnungen, deshalb steht überall der Link
 * zur offiziellen Seite.
 */
export type VisitInfo = {
  address: string;
  hours: string;
  closed: string;
  ticket: string;
  tip: string;
  website: string;
};

export const visitInfo: Record<string, VisitInfo> = {
  "louvre-paris": {
    address: "Rue de Rivoli, 75001 Paris",
    hours: "Mi–Mo 9:00–18:00, Fr bis 21:00",
    closed: "Dienstag",
    ticket: "ca. 22 €, unter 26 Jahren aus der EU frei",
    tip: "Zeitfenster online buchen und über den Eingang Porte des Lions kommen — dort steht fast niemand. Die Mona Lisa früh am Morgen ansteuern, danach in Ruhe die italienischen Säle.",
    website: "https://www.louvre.fr",
  },
  "orsay-paris": {
    address: "Esplanade Valéry Giscard d'Estaing, 75007 Paris",
    hours: "Di–So 9:30–18:00, Do bis 21:45",
    closed: "Montag",
    ticket: "ca. 16 €",
    tip: "Mit der Rolltreppe direkt in den 5. Stock zu den Impressionisten und von oben nach unten laufen. Donnerstagabend ist das Haus fast leer.",
    website: "https://www.musee-orsay.fr",
  },
  "marmottan-paris": {
    address: "2 Rue Louis Boilly, 75016 Paris",
    hours: "Di–So 10:00–18:00, Do bis 21:00",
    closed: "Montag",
    ticket: "ca. 14 €",
    tip: "Klein und selten voll. Erst ins Untergeschoss zu „Impression, Sonnenaufgang“, danach die Seerosen-Räume.",
    website: "https://www.marmottan.fr",
  },
  "pompidou-paris": {
    address: "Place Georges-Pompidou, 75004 Paris",
    hours: "Mi–Mo 11:00–21:00",
    closed: "Dienstag",
    ticket: "ca. 15 €",
    tip: "Das Haus wird saniert — vorher prüfen, welche Sammlungsteile geöffnet sind. Die Rolltreppe an der Fassade lohnt allein für den Blick über Paris.",
    website: "https://www.centrepompidou.fr",
  },
  "toulouse-lautrec-albi": {
    address: "Palais de la Berbie, 81000 Albi",
    hours: "Tgl. 10:00–18:00 (Winter kürzer)",
    closed: "Januar teilweise",
    ticket: "ca. 12 €",
    tip: "Nach der Sammlung durch den Bischofsgarten laufen — von dort der beste Blick auf den Tarn.",
    website: "https://www.musee-toulouse-lautrec.com",
  },
  "national-gallery-london": {
    address: "Trafalgar Square, London WC2N 5DN",
    hours: "Tgl. 10:00–18:00, Fr bis 21:00",
    closed: "24.–26. Dezember",
    ticket: "Eintritt frei",
    tip: "Der Sainsbury Wing mit der Frührenaissance ist der ruhigste Teil. Freitagabend gibt es Führungen ohne Anmeldung.",
    website: "https://www.nationalgallery.org.uk",
  },
  "courtauld-london": {
    address: "Somerset House, Strand, London WC2R 0RN",
    hours: "Tgl. 10:00–18:00",
    closed: "Feiertage im Winter",
    ticket: "ca. £ 12, unter 18 frei",
    tip: "In zwei Stunden gut zu schaffen. Manets „Bar in den Folies-Bergère“ hängt im zweiten Stock, davor eine Bank zum Sitzenbleiben.",
    website: "https://courtauld.ac.uk/gallery",
  },
  "national-galleries-edinburgh": {
    address: "The Mound, Edinburgh EH2 2EL",
    hours: "Tgl. 10:00–17:00, Do bis 19:00",
    closed: "25./26. Dezember",
    ticket: "Eintritt frei",
    tip: "Die schottischen Säle im Untergeschoss werden von Besuchern oft übersehen — genau dort hängen die stärksten Landschaften.",
    website: "https://www.nationalgalleries.org",
  },
  "prado-madrid": {
    address: "C. de Ruiz de Alarcón 23, 28014 Madrid",
    hours: "Mo–Sa 10:00–20:00, So 10:00–19:00",
    closed: "1. Januar, 1. Mai, 25. Dezember",
    ticket: "ca. 15 €, die letzten zwei Stunden frei",
    tip: "Die letzten zwei Stunden sind kostenlos, aber voll. Wer Velázquez in Ruhe will, kommt zur Öffnung und geht sofort in Saal 12.",
    website: "https://www.museodelprado.es",
  },
  "uffizien-florenz": {
    address: "Piazzale degli Uffizi 6, 50122 Florenz",
    hours: "Di–So 8:15–18:30",
    closed: "Montag",
    ticket: "ca. 25 € (Hochsaison)",
    tip: "Unbedingt vorab ein Zeitfenster buchen. Erster Slot um 8:15 heißt: Botticelli fast allein. Der Gang mit Blick auf den Arno ist der beste Pausenplatz.",
    website: "https://www.uffizi.it",
  },
  "accademia-venedig": {
    address: "Campo della Carità, 30123 Venedig",
    hours: "Di–So 8:15–19:15, Mo 8:15–14:00",
    closed: "Feiertage teils verkürzt",
    ticket: "ca. 15 €",
    tip: "Leonardos „Vitruvianischer Mensch“ ist lichtempfindlich und nur zeitweise ausgestellt — vorher auf der Website nachsehen.",
    website: "https://www.gallerieaccademia.it",
  },
  "sixtinische-kapelle": {
    address: "Vatikanische Museen, 00120 Vatikanstadt",
    hours: "Mo–Sa 8:00–19:00 (letzter Einlass 17:00)",
    closed: "Sonntag (außer letzter Sonntag im Monat)",
    ticket: "ca. 20 € (Vatikanische Museen)",
    tip: "Der Weg führt erst durch die kompletten Vatikanischen Museen — zwei Stunden einplanen. In der Kapelle gilt Fotoverbot und Schweigegebot, Schultern bedecken.",
    website: "https://www.museivaticani.va",
  },
  "stanza-della-segnatura": {
    address: "Raffael-Räume, Vatikanische Museen, Vatikanstadt",
    hours: "Mo–Sa 8:00–19:00",
    closed: "Sonntag (außer letzter Sonntag im Monat)",
    ticket: "im Ticket der Vatikanischen Museen enthalten",
    tip: "Liegt kurz vor der Sixtinischen Kapelle. Nicht durchlaufen: „Die Schule von Athen“ hängt rechts, gegenüber am besten stehen bleiben.",
    website: "https://www.museivaticani.va",
  },
  "san-luigi-dei-francesi": {
    address: "Piazza di S. Luigi de' Francesi, 00186 Rom",
    hours: "Mo–Fr 9:30–12:45 und 14:30–18:30, Sa/So kürzer",
    closed: "während der Messen",
    ticket: "Eintritt frei",
    tip: "Münzen mitbringen: Die Caravaggio-Kapelle wird nur gegen Einwurf beleuchtet. Mittags ist es dort am leersten.",
    website: "https://saintlouis-rome.net",
  },
  "palazzo-barberini-rom": {
    address: "Via delle Quattro Fontane 13, 00184 Rom",
    hours: "Di–So 10:00–19:00",
    closed: "Montag",
    ticket: "ca. 12 €",
    tip: "Selten voll, obwohl Caravaggio und Raffael hier hängen. Die Borromini-Treppe im Westflügel nicht auslassen.",
    website: "https://www.barberinicorsini.org",
  },
  "rijksmuseum-amsterdam": {
    address: "Museumstraat 1, 1071 XX Amsterdam",
    hours: "Tgl. 9:00–17:00",
    closed: "keine (nur 1. Januar)",
    ticket: "ca. 25 €, unter 18 frei",
    tip: "Um 9:00 in die Eregalerij gehen — die „Nachtwache“ hat dann noch Platz davor. Nachmittags ist die Bibliothek der ruhigste Raum im Haus.",
    website: "https://www.rijksmuseum.nl",
  },
  "mauritshuis-den-haag": {
    address: "Plein 29, 2511 CS Den Haag",
    hours: "Di–So 10:00–18:00, Mo 13:00–18:00",
    closed: "Montagvormittag",
    ticket: "ca. 19 €, unter 18 frei",
    tip: "Ein Stadtpalais mit nur 16 Räumen — in 90 Minuten machbar. Das „Mädchen mit dem Perlenohrring“ hängt in Saal 15 im Obergeschoss.",
    website: "https://www.mauritshuis.nl",
  },
  "kathedrale-antwerpen": {
    address: "Groenplaats 21, 2000 Antwerpen",
    hours: "Mo–Fr 10:00–17:00, Sa 10:00–15:00, So 13:00–17:00",
    closed: "während der Gottesdienste",
    ticket: "ca. 12 €",
    tip: "Die Rubens-Altäre stehen im Hauptschiff. Wenn die Orgel geprobt wird, ist der Besuch doppelt so viel wert.",
    website: "https://www.dekathedraal.be",
  },
  "alte-pinakothek-muenchen": {
    address: "Barer Str. 27, 80333 München",
    hours: "Di 10:00–20:30, Mi–So 10:00–18:00",
    closed: "Montag",
    ticket: "ca. 7 €, sonntags 1 €",
    tip: "Sonntags kostet der Eintritt 1 € — dann aber früh kommen. Der Rubens-Saal im Obergeschoss ist der größte Raum des Hauses.",
    website: "https://www.pinakothek.de",
  },
  "lenbachhaus-muenchen": {
    address: "Luisenstr. 33, 80333 München",
    hours: "Di 10:00–20:00, Mi–So 10:00–18:00",
    closed: "Montag",
    ticket: "ca. 10 €",
    tip: "Die weltweit größte Sammlung zum Blauen Reiter liegt im Obergeschoss des Altbaus. Der Café-Innenhof ist der schönste Pausenort im Kunstareal.",
    website: "https://www.lenbachhaus.de",
  },
  "gemaeldegalerie-dresden": {
    address: "Zwinger, Theaterplatz 1, 01067 Dresden",
    hours: "Di–So 10:00–18:00",
    closed: "Montag",
    ticket: "ca. 14 € (Zwinger-Kombiticket)",
    tip: "Die Sixtinische Madonna hängt am Ende der Mittelachse — bewusst so inszeniert. Von dort rückwärts durch die Säle laufen.",
    website: "https://gemaeldegalerie.skd.museum",
  },
  "alte-nationalgalerie-berlin": {
    address: "Bodestr. 1-3, 10178 Berlin",
    hours: "Di–So 10:00–18:00, Do bis 20:00",
    closed: "Montag",
    ticket: "ca. 12 €, unter 18 frei",
    tip: "Friedrichs „Mönch am Meer“ hängt im 3. Stock. Donnerstagabend ist die Museumsinsel deutlich ruhiger.",
    website: "https://www.smb.museum/museen-einrichtungen/alte-nationalgalerie",
  },
  "hamburger-kunsthalle": {
    address: "Glockengießerwall 5, 20095 Hamburg",
    hours: "Di–So 10:00–18:00, Do bis 21:00",
    closed: "Montag",
    ticket: "ca. 16 €",
    tip: "Der „Wanderer über dem Nebelmeer“ hängt im Altbau, 1. Obergeschoss. Danach durch die Verbindungsbrücke in die Galerie der Gegenwart.",
    website: "https://www.hamburger-kunsthalle.de",
  },
  "museum-ludwig-koeln": {
    address: "Heinrich-Böll-Platz, 50667 Köln",
    hours: "Di–So 10:00–18:00, jeden 1. Do bis 22:00",
    closed: "Montag",
    ticket: "ca. 12 €",
    tip: "Direkt neben dem Dom und dem Hauptbahnhof — perfekt für zwei Stunden zwischen zwei Zügen.",
    website: "https://www.museum-ludwig.de",
  },
  "kunsthistorisches-museum-wien": {
    address: "Maria-Theresien-Platz, 1010 Wien",
    hours: "Di–So 10:00–18:00, Do bis 21:00",
    closed: "Montag (Juni–August täglich offen)",
    ticket: "ca. 21 €, unter 19 frei",
    tip: "Die Bruegel-Säle sind das Herz des Hauses. Das Café unter der Kuppel gehört zu den schönsten Wiens — Zwischenstopp einplanen.",
    website: "https://www.khm.at",
  },
  "belvedere-wien": {
    address: "Prinz-Eugen-Str. 27, 1030 Wien",
    hours: "Tgl. 9:00–18:00",
    closed: "keine",
    ticket: "ca. 17 €",
    tip: "Klimts „Kuss“ hängt im Oberen Belvedere im 1. Stock und ist ab 11 Uhr belagert. Um 9:00 kommen, danach durch den Barockgarten hinunter.",
    website: "https://www.belvedere.at",
  },
  "albertina-wien": {
    address: "Albertinaplatz 1, 1010 Wien",
    hours: "Tgl. 10:00–18:00, Mi und Fr bis 21:00",
    closed: "keine",
    ticket: "ca. 20 €",
    tip: "Dürers „Feldhase“ ist ein Blatt auf Papier und nur selten im Original zu sehen — sonst hängt ein Faksimile. Vorab nachfragen lohnt sich.",
    website: "https://www.albertina.at",
  },
  "kunsthaus-zuerich": {
    address: "Heimplatz 1, 8001 Zürich",
    hours: "Di/Fr–So 10:00–18:00, Mi/Do 10:00–20:00",
    closed: "Montag",
    ticket: "ca. CHF 24, mittwochs Sammlung frei",
    tip: "Mittwochs ist die Sammlung gratis. Der Chipperfield-Neubau gegenüber ist über eine Unterführung angebunden.",
    website: "https://www.kunsthaus.ch",
  },
  "nasjonalmuseet-oslo": {
    address: "Brynjulf Bulls plass 3, 0250 Oslo",
    hours: "Di–So 10:00–17:00, Do bis 21:00",
    closed: "Montag",
    ticket: "ca. NOK 200, unter 18 frei",
    tip: "Der Munch-Saal liegt im 2. Stock. Danach hoch auf die Dachterrasse „Lyshallen“ — Blick über den Fjord inklusive.",
    website: "https://www.nasjonalmuseet.no",
  },
  "tretjakow-moskau": {
    address: "Lawruschinski-Gasse 10, Moskau",
    hours: "Di–So 10:00–18:00, Do/Fr bis 21:00",
    closed: "Montag",
    ticket: "vor Ort unterschiedlich",
    tip: "Reisehinweise des Auswärtigen Amts beachten. Wer nicht hinkann: Viele Räume sind als virtueller Rundgang online.",
    website: "https://www.tretyakovgallery.ru",
  },
  "art-institute-chicago": {
    address: "111 S Michigan Ave, Chicago, IL 60603",
    hours: "Do–Mo 11:00–17:00, Do bis 20:00",
    closed: "Dienstag und Mittwoch",
    ticket: "ca. $ 32, unter 14 frei",
    tip: "Dienstag und Mittwoch geschlossen — häufigster Reisefehler. Die Impressionisten hängen im 2. Stock des Allerton Building.",
    website: "https://www.artic.edu",
  },
  "national-gallery-washington": {
    address: "6th & Constitution Ave NW, Washington, DC",
    hours: "Tgl. 10:00–17:00",
    closed: "25. Dezember, 1. Januar",
    ticket: "Eintritt frei",
    tip: "Der West Building hat das einzige Leonardo-Gemälde Amerikas. Der Tunnel zum East Building mit der Lichtinstallation ist selbst eine Attraktion.",
    website: "https://www.nga.gov",
  },
  "phillips-collection-washington": {
    address: "1600 21st St NW, Washington, DC",
    hours: "Di–So 10:00–17:00, Do bis 20:00",
    closed: "Montag",
    ticket: "ca. $ 20, dienstags frei",
    tip: "Der Rothko Room fasst nur wenige Personen — dort ein paar Minuten sitzen bleiben, dafür ist er gebaut.",
    website: "https://www.phillipscollection.org",
  },
  "moma-new-york": {
    address: "11 W 53rd St, New York, NY 10019",
    hours: "Tgl. 10:30–17:30, Sa bis 19:00",
    closed: "Thanksgiving, 25. Dezember",
    ticket: "ca. $ 30, freitags ab 17:30 frei",
    tip: "Freitags ab 17:30 freier Eintritt, dafür sehr voll. Mit Etage 5 anfangen (van Gogh, Picasso) und nach unten arbeiten.",
    website: "https://www.moma.org",
  },
  "guggenheim-new-york": {
    address: "1071 5th Ave, New York, NY 10128",
    hours: "So–Fr 11:00–18:00, Sa bis 20:00",
    closed: "Donnerstag (saisonal)",
    ticket: "ca. $ 30, samstags abends „pay what you wish“",
    tip: "Mit dem Aufzug ganz nach oben und die Rampe hinunterlaufen — so war der Bau von Wright gedacht.",
    website: "https://www.guggenheim.org",
  },
  "neue-galerie-new-york": {
    address: "1048 5th Ave, New York, NY 10028",
    hours: "Do–Mo 11:00–18:00",
    closed: "Dienstag und Mittwoch",
    ticket: "ca. $ 28, erster Freitag im Monat frei",
    tip: "Klein und streng: Taschen müssen abgegeben werden, unter 12 Jahren kein Zutritt. Das Café Sabarsky serviert Wiener Kaffeehauskultur.",
    website: "https://www.neuegalerie.org",
  },
  "mfa-boston": {
    address: "465 Huntington Ave, Boston, MA 02115",
    hours: "Mi–So 10:00–17:00, Do/Fr bis 22:00",
    closed: "Montag und Dienstag",
    ticket: "ca. $ 27, unter 17 nachmittags frei",
    tip: "Donnerstag- und Freitagabend ist das Haus lange offen und fast leer — die beste Zeit für die Impressionisten-Flügel.",
    website: "https://www.mfa.org",
  },
  "walker-art-center-minneapolis": {
    address: "725 Vineland Pl, Minneapolis, MN 55403",
    hours: "Mi–So 11:00–17:00, Do bis 21:00",
    closed: "Montag und Dienstag",
    ticket: "ca. $ 18, Skulpturengarten frei",
    tip: "Der Skulpturengarten gegenüber ist kostenlos und ganzjährig offen — auch wenn das Museum geschlossen hat.",
    website: "https://walkerart.org",
  },
};

export function getVisitInfo(slug: string): VisitInfo | undefined {
  return visitInfo[slug];
}
