/**
 * Farbmuster für die Reise: historische Pigmentnamen bekommen eine sichtbare Farbe
 * und eine kurze Erklärung, woher sie stammen. Rein redaktionell, keine externen Daten.
 */
export type PigmentSwatch = { hex: string; note: string };

const swatches: Record<string, PigmentSwatch> = {
  Blattgold: { hex: "#c9a227", note: "Hauchdünn geschlagenes Gold, poliert bis es im Kerzenlicht glüht." },
  Azurit: { hex: "#2f6f9f", note: "Gemahlenes Kupfermineral — günstiger als Lapislazuli, aber grünstichig." },
  Azuritblau: { hex: "#2f6f9f", note: "Gemahlenes Kupfermineral — das Alltagsblau vor dem Ultramarin." },
  Ultramarin: { hex: "#26418f", note: "Aus afghanischem Lapislazuli; im Mittelalter teurer als Gold." },
  "Natürliches Ultramarin": { hex: "#26418f", note: "Echtes Lapislazuli-Blau, dem Mantel Marias vorbehalten." },
  Kobaltblau: { hex: "#0047ab", note: "Ab 1802 industriell hergestellt — kühl, deckend, lichtecht." },
  Preußischblau: { hex: "#0b3c5d", note: "Erstes synthetisches Blau (1706), tief und fast schwarz in der Masse." },
  Himmelblau: { hex: "#8fc1e3", note: "Mit Weiß aufgehelltes Blau für Luft und Ferne." },
  "Kaltes Blau": { hex: "#4a6f9c", note: "Blau mit Grauanteil — schiebt Bildteile in die Tiefe." },
  Blau: { hex: "#3b5ea6", note: "Sammelbegriff für die blauen Töne der Palette." },
  Blaugrau: { hex: "#7b8a99", note: "Gebrochenes Blau für Dunst, Stein und Schatten." },
  Zinnober: { hex: "#e34234", note: "Aus Quecksilbererz gewonnen, leuchtend und giftig." },
  Zinnoberrot: { hex: "#e34234", note: "Das kräftigste Rot der Alten Meister." },
  Karmin: { hex: "#960018", note: "Aus Cochenille-Schildläusen — tiefes, transparentes Rot." },
  Karminrot: { hex: "#960018", note: "Lasurrot aus Läusen, ideal für Samt und Seide." },
  Krapplack: { hex: "#a8324a", note: "Aus der Krappwurzel; als dünne Lasur über Rot gelegt." },
  Venezianischrot: { hex: "#a0392c", note: "Eisenoxidrot, erdig und sehr deckend." },
  Blutrot: { hex: "#7c1d1d", note: "Dunkles, sattes Rot für Dramatik im Bild." },
  Rot: { hex: "#c0392b", note: "Sammelbegriff für die roten Töne der Palette." },
  Rosa: { hex: "#e8b4bc", note: "Rot mit Bleiweiß gebrochen — Haut, Blüten, Seide." },
  Rosé: { hex: "#eec4c0", note: "Zartes Rosa der höfischen Malerei." },
  Rosaviolett: { hex: "#b57edc", note: "Zwischen Rosa und Violett — beliebt in der Moderne." },
  Violett: { hex: "#6f4a8e", note: "Erst mit synthetischen Farben zuverlässig verfügbar." },
  Primärrot: { hex: "#d0021b", note: "Reines Rot der Moderne, ohne Mischung aufgetragen." },
  Primärblau: { hex: "#0057b8", note: "Reines Blau der Moderne — Farbe als eigenständiges Element." },
  Primärgelb: { hex: "#f5c400", note: "Reines Gelb der Moderne, flächig und ungebrochen." },
  Ocker: { hex: "#c68e17", note: "Eisenhaltige Erde — das älteste Pigment der Menschheit." },
  Goldocker: { hex: "#d4a017", note: "Warmer, goldener Erdton für Licht auf Haut und Stoff." },
  Erdbraun: { hex: "#8b5a2b", note: "Gebrannte Erde für Böden, Holz und Schatten." },
  Umbra: { hex: "#6b4423", note: "Manganhaltige Erde; gebrannt besonders warm und schnell trocknend." },
  Braun: { hex: "#7a5230", note: "Sammelbegriff für die braunen Erdtöne." },
  Graubraun: { hex: "#8a7f72", note: "Gebrochener Ton für Wände, Nebel und Kleidung." },
  Bitumenbraun: { hex: "#4a3728", note: "Asphaltbraun — schön tief, trocknet aber nie ganz durch." },
  Bleizinngelb: { hex: "#f1d066", note: "Warmes Gelb der Alten Meister, später vergessen." },
  Chromgelb: { hex: "#f2b705", note: "Grelles Gelb des 19. Jahrhunderts, geliebt von van Gogh." },
  Cadmiumgelb: { hex: "#ffd300", note: "Kräftig, deckend, lichtecht — ab etwa 1840 im Handel." },
  Zitronengelb: { hex: "#f7e14a", note: "Kühles, grünstichiges Gelb." },
  "Grüne Erde": { hex: "#79876a", note: "Sanftes Grün, klassisch als Untermalung für Hauttöne." },
  Kupfergrün: { hex: "#3f8f6f", note: "Grünspan aus Kupfer — leuchtend, aber unbeständig." },
  Malachitgrün: { hex: "#0bda51", note: "Gemahlener Malachit, das Grün der Mineralpaletten." },
  Smaragdgrün: { hex: "#2e8b57", note: "Brillantes Grün des 19. Jahrhunderts, arsenhaltig." },
  Viridiangrün: { hex: "#40826d", note: "Kühles, transparentes Grün für Schatten im Laub." },
  Olivgrün: { hex: "#6b7a3a", note: "Gebrochenes Grün aus Gelb und Schwarz." },
  Blassgrün: { hex: "#a8c3a0", note: "Aufgehelltes Grün für Frühlingslicht." },
  Säuregrün: { hex: "#b5e61d", note: "Grelles Grün der Moderne — bewusst künstlich." },
  Grün: { hex: "#4f7942", note: "Sammelbegriff für die grünen Töne der Palette." },
  Bleiweiß: { hex: "#f4f1ea", note: "Das Weiß der Alten Meister: deckend, geschmeidig, giftig." },
  Silberweiß: { hex: "#f2f3f4", note: "Feinstes Bleiweiß, kühl gebrochen." },
  Zinkweiß: { hex: "#fbfcfd", note: "Ab 1834 ungiftige Alternative, kühler und transparenter." },
  Kalkweiß: { hex: "#f6f4ec", note: "Weiß aus Kalk — Standard in der Freskomalerei." },
  Marmorweiß: { hex: "#f3f0e7", note: "Aus gemahlenem Marmor, leicht körnig." },
  Cremeweiß: { hex: "#f5ecd7", note: "Warmes Weiß für Licht auf Haut und Leinen." },
  Grauweiß: { hex: "#e6e5e0", note: "Weiß mit Grauanteil — hält das Bild ruhig." },
  Weiß: { hex: "#f7f7f4", note: "Weiß setzt Licht und mischt jede Farbe heller." },
  Beinschwarz: { hex: "#2b2b2b", note: "Aus verkohlten Knochen — tiefes, leicht bläuliches Schwarz." },
  Elfenbeinschwarz: { hex: "#232323", note: "Feinstes Schwarz, ursprünglich aus verkohltem Elfenbein." },
  Pflanzenschwarz: { hex: "#2f2f2c", note: "Aus verkohltem Holz oder Reben, warm im Ton." },
  Schwarz: { hex: "#1c1c1c", note: "Schwarz begrenzt Formen und vertieft Schatten." },
  Grau: { hex: "#8e8e8e", note: "Mischung aus Schwarz und Weiß — Grundlage der Untermalung." },
  Silbergrau: { hex: "#b9bcbf", note: "Kühles, helles Grau für Licht auf Metall und Stoff." },
  Silber: { hex: "#c0c0c0", note: "Metallglanz, oft mit Grau und Weiß gemalt." },
};

/** Farbe und Erklärung zu einem Palettennamen — mit ruhigem Standardwert. */
export function pigmentSwatch(name: string): PigmentSwatch {
  return swatches[name] ?? { hex: "#b9b3a6", note: "Historischer Farbton dieser Epoche." };
}
