/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as AuthenticatedSammlungRouteImport } from './routes/_authenticated/sammlung'
import { Route as EpochenEpocheRouteImport } from './routes/epochen.$epoche'
import { Route as MalerSlugRouteImport } from './routes/maler.$slug'
import { Route as WerkeIdRouteImport } from './routes/werke.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSammlungRoute = AuthenticatedSammlungRouteImport.update({
  id: '/sammlung',
  path: '/sammlung',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EpochenEpocheRoute = EpochenEpocheRouteImport.update({
  id: '/epochen/$epoche',
  path: '/epochen/$epoche',
  getParentRoute: () => rootRouteImport,
} as any)
const MalerSlugRoute = MalerSlugRouteImport.update({
  id: '/maler/$slug',
  path: '/maler/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WerkeIdRoute = WerkeIdRouteImport.update({
  id: '/werke/$id',
  path: '/werke/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/quiz': typeof QuizRoute
  '/sammlung': typeof AuthenticatedSammlungRoute
  '/epochen/$epoche': typeof EpochenEpocheRoute
  '/maler/$slug': typeof MalerSlugRoute
  '/werke/$id': typeof WerkeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/quiz': typeof QuizRoute
  '/sammlung': typeof AuthenticatedSammlungRoute
  '/epochen/$epoche': typeof EpochenEpocheRoute
  '/maler/$slug': typeof MalerSlugRoute
  '/werke/$id': typeof WerkeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/quiz': typeof QuizRoute
  '/_authenticated/sammlung': typeof AuthenticatedSammlungRoute
  '/epochen/$epoche': typeof EpochenEpocheRoute
  '/maler/$slug': typeof MalerSlugRoute
  '/werke/$id': typeof WerkeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/quiz'
    | '/sammlung'
    | '/epochen/$epoche'
    | '/maler/$slug'
    | '/werke/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/quiz'
    | '/sammlung'
    | '/epochen/$epoche'
    | '/maler/$slug'
    | '/werke/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/quiz'
    | '/_authenticated/sammlung'
    | '/epochen/$epoche'
    | '/maler/$slug'
    | '/werke/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  QuizRoute: typeof QuizRoute
  EpochenEpocheRoute: typeof EpochenEpocheRoute
  MalerSlugRoute: typeof MalerSlugRoute
  WerkeIdRoute: typeof WerkeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sammlung': {
      id: '/_authenticated/sammlung'
      path: '/sammlung'
      fullPath: '/sammlung'
      preLoaderRoute: typeof AuthenticatedSammlungRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/epochen/$epoche': {
      id: '/epochen/$epoche'
      path: '/epochen/$epoche'
      fullPath: '/epochen/$epoche'
      preLoaderRoute: typeof EpochenEpocheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maler/$slug': {
      id: '/maler/$slug'
      path: '/maler/$slug'
      fullPath: '/maler/$slug'
      preLoaderRoute: typeof MalerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/werke/$id': {
      id: '/werke/$id'
      path: '/werke/$id'
      fullPath: '/werke/$id'
      preLoaderRoute: typeof WerkeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSammlungRoute: typeof AuthenticatedSammlungRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSammlungRoute: AuthenticatedSammlungRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  QuizRoute: QuizRoute,
  EpochenEpocheRoute: EpochenEpocheRoute,
  MalerSlugRoute: MalerSlugRoute,
  WerkeIdRoute: WerkeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
